### ISSUE TITLE
[Bug] EasyEffects Daemon does not launch on boot when option is selected

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [flathub/com.github.wwmm.easyeffects#3] opened 2021-08-24 09:40 UTC
### Description

When I select the option to start the service on login, it does not start the service. I have to always manually start EasyEffects.

### Steps to Reproduce

- Start EasyEffects and enable the option to start it at boot.
- Reboot the Computer.
- Login into the Desktop.

### Expected Result

The EasyEffects service should start when login into a desktop session.

### Observed Result

The EasyEffects service does not start on login.

### System Information

OS: Fedora 34
Desktop: Gnome 40.4
EasyEffects version: 6.1.0

**Comment by wwmm** [comment] 2021-08-24 14:11
That is a problem that affects the flatpak package for PulseEffects too https://github.com/flathub/com.github.wwmm.pulseeffects/issues/18. What that menu function does is creating an autostart file inside `~/.config/autostart/`. But the Flatpak sandbox forces the file to be created in its custom folder. For now you will have to create the file `~/.config/autostart/easyeffects-service.desktop` manually. I think that this content should still work
```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
```

**Comment by Sebastian-Hirsch** [comment] 2021-08-24 15:38
@wwmm I tried your suggested solution and it didn't work. The EasyEffects Service does not start at login with this .desktop file.

**Comment by wwmm** [comment] 2021-08-25 00:28
Is there any error when you run `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service` in a terminal? If this does not work in a terminal it is not going to work in the desktop file.

@vchernin do you have any suggestion about how to manually create an autostart file that works with the flatpak package?

**Comment by vchernin** [comment] 2021-08-25 00:39
> @vchernin do you have any suggestion about how to manually create an autostart file that works with the flatpak package?

I am not really sure. I know @Sebastian-Hirsch tried this out [in another thread](https://github.com/flathub/flathub/pull/2429#issuecomment-897990176), but they didn't seem to have any luck. 

I might try to workaround it myself later and see if I can give clear steps if so.

**Comment by wwmm** [comment] 2021-08-25 01:06
At least outside of flatpak this works
```
[Desktop Entry]
Name=EasyEffects
Comment=EasyEffects Service
Exec=easyeffects --gapplication-service
Icon=easyeffects
StartupNotify=false
Terminal=false
Type=Application
```
Like I said before the first step is getting the command to work in a terminal.

**Comment by Sebastian-Hirsch** [comment] 2021-08-25 07:22
@wwmm I could get it to work. Now it launches at start. I have added my autostart file to this message:
[com.github.wwmm.easyeffects.desktop.txt](https://github.com/flathub/com.github.wwmm.easyeffects/files/7044595/com.github.wwmm.easyeffects.desktop.txt)

**Comment by vchernin** [comment] 2021-08-25 16:04
> But the Flatpak sandbox forces the file to be created in its custom folder.

We could definitely poke holes in the sandbox to access most things in the host system, but it's not ideal at all, and furthermore libportal does seem to compile according to #5.

**Comment by DanMan** [comment] 2021-08-29 23:31
With such a .desktop file, it doesn't start minimized. Is that on purpose? I'd prefer it, if it started hidden/minimized. GWE does it that way.

**Comment by wwmm** [comment] 2021-08-30 00:18
>With such a .desktop file, it doesn't start minimized. Is that on purpose? I'd prefer it, if it started hidden/minimized. GWE does it that way.

Strange. The option `--gapplication-service` makes the program start in background with its window hidden. In my desktop EasyEffects autostarts in the background without showing any window. But I am not using the flatpak package. The only situation where our window is shown when `--gapplication-service` is used is the one where the user click on our desktop icon in the desktop application launcher. The autostart file should not be showing our window.

**Comment by vchernin** [comment] 2021-08-30 01:12
@DanMan could you rollback to the previous Flatpak update with `flatpak update --commit=f02d6ec9c68cc07512ba961b3fa117832ae6e5bb68899363280260b33fbaa4e3 com.github.wwmm.easyeffects`

I think it's possible https://github.com/flathub/com.github.wwmm.easyeffects/pull/2 caused a regression making it start not minimized.

**Comment by Sebastian-Hirsch** [comment] 2021-08-30 07:00
@vchernin ,@wwmm, @DanMan, I cannot reproduce the mentioned issue. EasyEffects always starts in the background for me with my config that I posted here. I use the latest stable release.

**Comment by vchernin** [comment] 2021-08-30 07:03
@DanMan, @Sebastian-Hirsch is on Fedora 34 and GNOME 40, what distro are you on?

**Comment by Sebastian-Hirsch** [comment] 2021-08-30 09:37
@vchernin I am also on Fedora 34 with Gnome 40.

**Comment by DanMan** [comment] 2021-08-30 19:06
It might not actually use the file at `~/.config/autostart/easyeffects-service.desktop` mentioned but `~/.config/autostart/com.github.wwmm.easyeffects.desktop`.

If I run  `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service` I get the error `Failed to register: Unable to acquire bus name 'com.github.wwmm.easyeffects'`. It works if I leave out the `--gapplication-service` at the end. That's also the command that's inside the `.desktop` file.

Fedora 33 with Gnome 3.38.5.

**Comment by vchernin** [comment] 2021-08-30 19:08
> It might not actually use the file at `~/.config/autostart/easyeffects-service.desktop` but `~/.config/autostart/com.github.wwmm.easyeffects.desktop`.

Have you tried both names for the service file?

@Sebastian-Hirsch what did you name your service file?

**Comment by vchernin** [comment] 2021-08-30 19:10
> `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service`
> That's also the command that's inside the .desktop file.

Are you confident you are on the latest version? A couple days ago there was an update which would have changed the desktop file to launch the `easyeffects-wrapper` binary instead of `easyeffects`.

**Comment by Sebastian-Hirsch** [comment] 2021-08-30 19:14
@vchernin I named the file com.github.wwmm.easyeffects.desktop.

**Comment by vchernin** [comment] 2021-08-30 19:16
> @vchernin I named the file com.github.wwmm.easyeffects.desktop.

Wait, you gave a service file a .desktop file extension? That sounds like it would cause problems...

**Comment by vchernin** [comment] 2021-08-30 19:18
> > @vchernin I named the file com.github.wwmm.easyeffects.desktop.
> 
> Wait, you gave a service file a .desktop file extension? That sounds like it would cause problems...

Oh never mind, I see that's what people did on the other thread too. My bad, yes what you did is right I think.

**Comment by DanMan** [comment] 2021-08-30 19:22
I'm on EasyEffect 6.1.0. I've added the autostart .desktop by adding EasyEffects through Gnome Tweaks autostart options. This creates the file `com.github.wwmm.easyeffects.desktop` at the location mentioned but without the `--gapplication-service` at the end. If I add that and reboot, it starts up on login but not minimized.

P.S.: I got the error `Failed to register: Unable to acquire bus name 'com.github.wwmm.easyeffects'` because EE was already running, sorry. It starts when it's not; and minimized.

But on login, the GUI is shown, so doesn't it actually use the file from `~/.config/autostart/com.github.wwmm.easyeffects.desktop` ?

**Comment by Sebastian-Hirsch** [comment] 2021-08-30 19:22
All files in this folder have a .desktop file ending so I gave that file one too.
![Bildschirmfoto von 2021-08-30 21-22-15](https://user-images.githubusercontent.com/41188546/131393405-a82a9cf9-0efa-41ce-a22f-93d8b434c513.png)

**Comment by Sebastian-Hirsch** [comment] 2021-08-30 19:24
@DanMan Do not add EasyEffects with gnome tweaks. Remove it in gnome tweaks and then use the file I added in this thread and it should work.

**Comment by DanMan** [comment] 2021-08-30 19:34
> @DanMan Do not add EasyEffects with gnome tweaks. Remove it in gnome tweaks and then use the file I added in this thread and it should work.

Ok, that actually worked. Really weird. 😕

Oh well, cheers. 👍

**Comment by vchernin** [comment] 2021-08-30 19:38
OK so to sum up the steps for future readers:

Add a file named `com.github.wwmm.easyeffects.desktop` to `~/.config/autostart`. Then add the contents:

```
[Desktop Entry]
Name=EasyEffects
Comment=EasyEffects Service
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=easyeffects com.github.wwmm.easyeffects --gapplication-service
Icon=easyeffects
StartupNotify=false
Terminal=false
Type=Application
```

Ensure to not add EasyEffects to GNOME Tweaks. The app should start minimized on log in. If you encounter errors ensure EasyEffects is not already running.

As before the actual solution is https://github.com/wwmm/easyeffects/issues/535. Once  that is implemented you shouldn't need to mess with config files.

**Comment by vchernin** [comment] 2021-09-17 22:42
This will be fixed with the next update onto Flathub stable in https://github.com/flathub/com.github.wwmm.easyeffects/pull/15. The portal will be used. It should be released in a few hours from writing.

If you've added a custom autostart file before nothing will change. But if you would prefer to use the portal just enable the switch, and grant EasyEffects permission to use the portal. Then the switch will work and will automatically create or remove the autostart per the state of the switch, just like you'd expect. The switch will overwrite the custom autostart file you might have added before.

If you do run into issues however try the following commands:

Remove the Flatpak and it's all data/user customization:
`flatpak remove com.github.wwmm.easyeffects --delete-data` 

Reset the permission for EasyEffects (meaning it will no longer be able to modify the autostart file for you):
`flatpak permission-reset com.github.wwmm.easyeffects`

**Closed** 2021-09-17 22:42 UTC

**Comment by sunbearc22** [comment] 2025-08-22 02:23
I did encounter having starting `easyeffects` via the Startup App in Ubuntu 24.04. I tried issuing various commands. Finally found this command worked: 
`flatpak run --branch=stable --arch=x86_64 com.github.wwmm.easyeffects`
